sudo: required
services:
  - docker

before_install:
  - docker build -t sudhrk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sudhrk/react-test npm test -- --coverage

after_success:
  - docker build -t sudhrk/multi-client ./client
  - docker build -t sudhrk/multi-nginx ./nginx
  - docker build -t sudhrk/multi-server ./server
  - docker build -t sudhrk/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take above images and push to Docker Hub
  - docker push sudhrk/multi-client
  - docker push sudhrk/multi-nginx
  - docker push sudhrk/multi-server
  - docker push sudhrk/multi-worker